[package]
name = "rustrays"
version = "0.21.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
fastrand = "1.9.0"
indicatif = "0.17.3"
rand = "0.8.5"
